/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../common/src/routes/__root'
import { Route as AppRouteImport } from './../../common/src/routes/_app'
import { Route as LoginRouteImport } from './../../common/src/routes/login'
import { Route as AppIndexRouteImport } from './../../common/src/routes/_app/index'
import { Route as AppDeployRouteImport } from './../../common/src/routes/_app/deploy'
import { Route as AppHarnessesRouteImport } from './../../common/src/routes/_app/harnesses'
import { Route as AppOptimizationRouteImport } from './../../common/src/routes/_app/optimization'
import { Route as AppRouterRouteImport } from './../../common/src/routes/_app/router'
import { Route as AppStatusRouteImport } from './../../common/src/routes/_app/status'
import { Route as AppTokenopsRouteImport } from './../../common/src/routes/_app/tokenops'
import { Route as AppAccountAppearanceRouteImport } from './../../common/src/routes/_app/account.appearance'
import { Route as AppAccountPasswordRouteImport } from './../../common/src/routes/_app/account.password'
import { Route as AppAgentsIndexRouteImport } from './../../common/src/routes/_app/agents.index'
import { Route as AppAgentsAgentIdRouteImport } from './../../common/src/routes/_app/agents.$agentId'
import { Route as AppAgentsMineRouteImport } from './../../common/src/routes/_app/agents.mine'
import { Route as AppBuildsIndexRouteImport } from './../../common/src/routes/_app/builds.index'
import { Route as AppBuildsBuildIdRouteImport } from './../../common/src/routes/_app/builds.$buildId'
import { Route as AppChatIndexRouteImport } from './../../common/src/routes/_app/chat.index'
import { Route as AppChatSessionIdRouteImport } from './../../common/src/routes/_app/chat.$sessionId'
import { Route as AppFlowsIndexRouteImport } from './../../common/src/routes/_app/flows.index'
import { Route as AppFlowsFlowIdRouteImport } from './../../common/src/routes/_app/flows.$flowId'
import { Route as AppMcpIndexRouteImport } from './../../common/src/routes/_app/mcp.index'
import { Route as AppMcpConnectorIdRouteImport } from './../../common/src/routes/_app/mcp.$connectorId'
import { Route as AppSessionsIndexRouteImport } from './../../common/src/routes/_app/sessions.index'
import { Route as AppSessionsSessionIdRouteImport } from './../../common/src/routes/_app/sessions.$sessionId'
import { Route as AppSettingsIndexRouteImport } from './../../common/src/routes/_app/settings.index'
import { Route as AppSettingsAppearanceRouteImport } from './../../common/src/routes/_app/settings.appearance'
import { Route as AppSettingsChatContextRouteImport } from './../../common/src/routes/_app/settings.chat-context'
import { Route as AppSettingsOptimizationRouteImport } from './../../common/src/routes/_app/settings.optimization'
import { Route as AppSettingsOptimizationTiersRouteImport } from './../../common/src/routes/_app/settings.optimization-tiers'
import { Route as AppSettingsPasswordRouteImport } from './../../common/src/routes/_app/settings.password'
import { Route as AppSettingsSecretsRouteImport } from './../../common/src/routes/_app/settings.secrets'
import { Route as AppWorkflowsIndexRouteImport } from './../../common/src/routes/_app/workflows.index'
import { Route as AppWorkflowsWorkflowIdRouteImport } from './../../common/src/routes/_app/workflows.$workflowId'
import { Route as AppWorkflowsDraftsRouteImport } from './../../common/src/routes/_app/workflows.drafts'
import { Route as AppWorkflowsNewRouteImport } from './../../common/src/routes/_app/workflows.new'
import { Route as AppWorkflowsRunsRouteImport } from './../../common/src/routes/_app/workflows.runs'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDeployRoute = AppDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => AppRoute,
} as any)
const AppHarnessesRoute = AppHarnessesRouteImport.update({
  id: '/harnesses',
  path: '/harnesses',
  getParentRoute: () => AppRoute,
} as any)
const AppOptimizationRoute = AppOptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => AppRoute,
} as any)
const AppRouterRoute = AppRouterRouteImport.update({
  id: '/router',
  path: '/router',
  getParentRoute: () => AppRoute,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRoute,
} as any)
const AppTokenopsRoute = AppTokenopsRouteImport.update({
  id: '/tokenops',
  path: '/tokenops',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountAppearanceRoute = AppAccountAppearanceRouteImport.update({
  id: '/account/appearance',
  path: '/account/appearance',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountPasswordRoute = AppAccountPasswordRouteImport.update({
  id: '/account/password',
  path: '/account/password',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsMineRoute = AppAgentsMineRouteImport.update({
  id: '/agents/mine',
  path: '/agents/mine',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildsIndexRoute = AppBuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => AppRoute,
} as any)
const AppBuildsBuildIdRoute = AppBuildsBuildIdRouteImport.update({
  id: '/builds/$buildId',
  path: '/builds/$buildId',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatSessionIdRoute = AppChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsIndexRoute = AppFlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsFlowIdRoute = AppFlowsFlowIdRouteImport.update({
  id: '/flows/$flowId',
  path: '/flows/$flowId',
  getParentRoute: () => AppRoute,
} as any)
const AppMcpIndexRoute = AppMcpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => AppRoute,
} as any)
const AppMcpConnectorIdRoute = AppMcpConnectorIdRouteImport.update({
  id: '/mcp/$connectorId',
  path: '/mcp/$connectorId',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/settings/appearance',
  path: '/settings/appearance',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsChatContextRoute = AppSettingsChatContextRouteImport.update({
  id: '/settings/chat-context',
  path: '/settings/chat-context',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsOptimizationRoute = AppSettingsOptimizationRouteImport.update({
  id: '/settings/optimization',
  path: '/settings/optimization',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsOptimizationTiersRoute =
  AppSettingsOptimizationTiersRouteImport.update({
    id: '/settings/optimization-tiers',
    path: '/settings/optimization-tiers',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsPasswordRoute = AppSettingsPasswordRouteImport.update({
  id: '/settings/password',
  path: '/settings/password',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecretsRoute = AppSettingsSecretsRouteImport.update({
  id: '/settings/secrets',
  path: '/settings/secrets',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsWorkflowIdRoute = AppWorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsDraftsRoute = AppWorkflowsDraftsRouteImport.update({
  id: '/workflows/drafts',
  path: '/workflows/drafts',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsNewRoute = AppWorkflowsNewRouteImport.update({
  id: '/workflows/new',
  path: '/workflows/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRunsRoute = AppWorkflowsRunsRouteImport.update({
  id: '/workflows/runs',
  path: '/workflows/runs',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/deploy': typeof AppDeployRoute
  '/harnesses': typeof AppHarnessesRoute
  '/optimization': typeof AppOptimizationRoute
  '/router': typeof AppRouterRoute
  '/status': typeof AppStatusRoute
  '/tokenops': typeof AppTokenopsRoute
  '/account/appearance': typeof AppAccountAppearanceRoute
  '/account/password': typeof AppAccountPasswordRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/agents/mine': typeof AppAgentsMineRoute
  '/builds/$buildId': typeof AppBuildsBuildIdRoute
  '/chat/$sessionId': typeof AppChatSessionIdRoute
  '/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/mcp/$connectorId': typeof AppMcpConnectorIdRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/chat-context': typeof AppSettingsChatContextRoute
  '/settings/optimization': typeof AppSettingsOptimizationRoute
  '/settings/optimization-tiers': typeof AppSettingsOptimizationTiersRoute
  '/settings/password': typeof AppSettingsPasswordRoute
  '/settings/secrets': typeof AppSettingsSecretsRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/workflows/drafts': typeof AppWorkflowsDraftsRoute
  '/workflows/new': typeof AppWorkflowsNewRoute
  '/workflows/runs': typeof AppWorkflowsRunsRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/builds/': typeof AppBuildsIndexRoute
  '/chat/': typeof AppChatIndexRoute
  '/flows/': typeof AppFlowsIndexRoute
  '/mcp/': typeof AppMcpIndexRoute
  '/sessions/': typeof AppSessionsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/workflows/': typeof AppWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/deploy': typeof AppDeployRoute
  '/harnesses': typeof AppHarnessesRoute
  '/optimization': typeof AppOptimizationRoute
  '/router': typeof AppRouterRoute
  '/status': typeof AppStatusRoute
  '/tokenops': typeof AppTokenopsRoute
  '/': typeof AppIndexRoute
  '/account/appearance': typeof AppAccountAppearanceRoute
  '/account/password': typeof AppAccountPasswordRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/agents/mine': typeof AppAgentsMineRoute
  '/builds/$buildId': typeof AppBuildsBuildIdRoute
  '/chat/$sessionId': typeof AppChatSessionIdRoute
  '/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/mcp/$connectorId': typeof AppMcpConnectorIdRoute
  '/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/chat-context': typeof AppSettingsChatContextRoute
  '/settings/optimization': typeof AppSettingsOptimizationRoute
  '/settings/optimization-tiers': typeof AppSettingsOptimizationTiersRoute
  '/settings/password': typeof AppSettingsPasswordRoute
  '/settings/secrets': typeof AppSettingsSecretsRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/workflows/drafts': typeof AppWorkflowsDraftsRoute
  '/workflows/new': typeof AppWorkflowsNewRoute
  '/workflows/runs': typeof AppWorkflowsRunsRoute
  '/agents': typeof AppAgentsIndexRoute
  '/builds': typeof AppBuildsIndexRoute
  '/chat': typeof AppChatIndexRoute
  '/flows': typeof AppFlowsIndexRoute
  '/mcp': typeof AppMcpIndexRoute
  '/sessions': typeof AppSessionsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/workflows': typeof AppWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/deploy': typeof AppDeployRoute
  '/_app/harnesses': typeof AppHarnessesRoute
  '/_app/optimization': typeof AppOptimizationRoute
  '/_app/router': typeof AppRouterRoute
  '/_app/status': typeof AppStatusRoute
  '/_app/tokenops': typeof AppTokenopsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/account/appearance': typeof AppAccountAppearanceRoute
  '/_app/account/password': typeof AppAccountPasswordRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/_app/agents/mine': typeof AppAgentsMineRoute
  '/_app/builds/$buildId': typeof AppBuildsBuildIdRoute
  '/_app/chat/$sessionId': typeof AppChatSessionIdRoute
  '/_app/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/_app/mcp/$connectorId': typeof AppMcpConnectorIdRoute
  '/_app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/chat-context': typeof AppSettingsChatContextRoute
  '/_app/settings/optimization': typeof AppSettingsOptimizationRoute
  '/_app/settings/optimization-tiers': typeof AppSettingsOptimizationTiersRoute
  '/_app/settings/password': typeof AppSettingsPasswordRoute
  '/_app/settings/secrets': typeof AppSettingsSecretsRoute
  '/_app/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/_app/workflows/drafts': typeof AppWorkflowsDraftsRoute
  '/_app/workflows/new': typeof AppWorkflowsNewRoute
  '/_app/workflows/runs': typeof AppWorkflowsRunsRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/builds/': typeof AppBuildsIndexRoute
  '/_app/chat/': typeof AppChatIndexRoute
  '/_app/flows/': typeof AppFlowsIndexRoute
  '/_app/mcp/': typeof AppMcpIndexRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/workflows/': typeof AppWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/deploy'
    | '/harnesses'
    | '/optimization'
    | '/router'
    | '/status'
    | '/tokenops'
    | '/account/appearance'
    | '/account/password'
    | '/agents/$agentId'
    | '/agents/mine'
    | '/builds/$buildId'
    | '/chat/$sessionId'
    | '/flows/$flowId'
    | '/mcp/$connectorId'
    | '/sessions/$sessionId'
    | '/settings/appearance'
    | '/settings/chat-context'
    | '/settings/optimization'
    | '/settings/optimization-tiers'
    | '/settings/password'
    | '/settings/secrets'
    | '/workflows/$workflowId'
    | '/workflows/drafts'
    | '/workflows/new'
    | '/workflows/runs'
    | '/agents/'
    | '/builds/'
    | '/chat/'
    | '/flows/'
    | '/mcp/'
    | '/sessions/'
    | '/settings/'
    | '/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/deploy'
    | '/harnesses'
    | '/optimization'
    | '/router'
    | '/status'
    | '/tokenops'
    | '/'
    | '/account/appearance'
    | '/account/password'
    | '/agents/$agentId'
    | '/agents/mine'
    | '/builds/$buildId'
    | '/chat/$sessionId'
    | '/flows/$flowId'
    | '/mcp/$connectorId'
    | '/sessions/$sessionId'
    | '/settings/appearance'
    | '/settings/chat-context'
    | '/settings/optimization'
    | '/settings/optimization-tiers'
    | '/settings/password'
    | '/settings/secrets'
    | '/workflows/$workflowId'
    | '/workflows/drafts'
    | '/workflows/new'
    | '/workflows/runs'
    | '/agents'
    | '/builds'
    | '/chat'
    | '/flows'
    | '/mcp'
    | '/sessions'
    | '/settings'
    | '/workflows'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/deploy'
    | '/_app/harnesses'
    | '/_app/optimization'
    | '/_app/router'
    | '/_app/status'
    | '/_app/tokenops'
    | '/_app/'
    | '/_app/account/appearance'
    | '/_app/account/password'
    | '/_app/agents/$agentId'
    | '/_app/agents/mine'
    | '/_app/builds/$buildId'
    | '/_app/chat/$sessionId'
    | '/_app/flows/$flowId'
    | '/_app/mcp/$connectorId'
    | '/_app/sessions/$sessionId'
    | '/_app/settings/appearance'
    | '/_app/settings/chat-context'
    | '/_app/settings/optimization'
    | '/_app/settings/optimization-tiers'
    | '/_app/settings/password'
    | '/_app/settings/secrets'
    | '/_app/workflows/$workflowId'
    | '/_app/workflows/drafts'
    | '/_app/workflows/new'
    | '/_app/workflows/runs'
    | '/_app/agents/'
    | '/_app/builds/'
    | '/_app/chat/'
    | '/_app/flows/'
    | '/_app/mcp/'
    | '/_app/sessions/'
    | '/_app/settings/'
    | '/_app/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deploy': {
      id: '/_app/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof AppDeployRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/harnesses': {
      id: '/_app/harnesses'
      path: '/harnesses'
      fullPath: '/harnesses'
      preLoaderRoute: typeof AppHarnessesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/optimization': {
      id: '/_app/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof AppOptimizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/router': {
      id: '/_app/router'
      path: '/router'
      fullPath: '/router'
      preLoaderRoute: typeof AppRouterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/status': {
      id: '/_app/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tokenops': {
      id: '/_app/tokenops'
      path: '/tokenops'
      fullPath: '/tokenops'
      preLoaderRoute: typeof AppTokenopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/appearance': {
      id: '/_app/account/appearance'
      path: '/account/appearance'
      fullPath: '/account/appearance'
      preLoaderRoute: typeof AppAccountAppearanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/password': {
      id: '/_app/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AppAccountPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/mine': {
      id: '/_app/agents/mine'
      path: '/agents/mine'
      fullPath: '/agents/mine'
      preLoaderRoute: typeof AppAgentsMineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/builds/': {
      id: '/_app/builds/'
      path: '/builds'
      fullPath: '/builds/'
      preLoaderRoute: typeof AppBuildsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/builds/$buildId': {
      id: '/_app/builds/$buildId'
      path: '/builds/$buildId'
      fullPath: '/builds/$buildId'
      preLoaderRoute: typeof AppBuildsBuildIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/': {
      id: '/_app/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$sessionId': {
      id: '/_app/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof AppChatSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flows/': {
      id: '/_app/flows/'
      path: '/flows'
      fullPath: '/flows/'
      preLoaderRoute: typeof AppFlowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flows/$flowId': {
      id: '/_app/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof AppFlowsFlowIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mcp/': {
      id: '/_app/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof AppMcpIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mcp/$connectorId': {
      id: '/_app/mcp/$connectorId'
      path: '/mcp/$connectorId'
      fullPath: '/mcp/$connectorId'
      preLoaderRoute: typeof AppMcpConnectorIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$sessionId': {
      id: '/_app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/chat-context': {
      id: '/_app/settings/chat-context'
      path: '/settings/chat-context'
      fullPath: '/settings/chat-context'
      preLoaderRoute: typeof AppSettingsChatContextRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/optimization': {
      id: '/_app/settings/optimization'
      path: '/settings/optimization'
      fullPath: '/settings/optimization'
      preLoaderRoute: typeof AppSettingsOptimizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/optimization-tiers': {
      id: '/_app/settings/optimization-tiers'
      path: '/settings/optimization-tiers'
      fullPath: '/settings/optimization-tiers'
      preLoaderRoute: typeof AppSettingsOptimizationTiersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/password': {
      id: '/_app/settings/password'
      path: '/settings/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof AppSettingsPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/secrets': {
      id: '/_app/settings/secrets'
      path: '/settings/secrets'
      fullPath: '/settings/secrets'
      preLoaderRoute: typeof AppSettingsSecretsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/': {
      id: '/_app/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/$workflowId': {
      id: '/_app/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/drafts': {
      id: '/_app/workflows/drafts'
      path: '/workflows/drafts'
      fullPath: '/workflows/drafts'
      preLoaderRoute: typeof AppWorkflowsDraftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/new': {
      id: '/_app/workflows/new'
      path: '/workflows/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof AppWorkflowsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/runs': {
      id: '/_app/workflows/runs'
      path: '/workflows/runs'
      fullPath: '/workflows/runs'
      preLoaderRoute: typeof AppWorkflowsRunsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDeployRoute: typeof AppDeployRoute
  AppHarnessesRoute: typeof AppHarnessesRoute
  AppOptimizationRoute: typeof AppOptimizationRoute
  AppRouterRoute: typeof AppRouterRoute
  AppStatusRoute: typeof AppStatusRoute
  AppTokenopsRoute: typeof AppTokenopsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountAppearanceRoute: typeof AppAccountAppearanceRoute
  AppAccountPasswordRoute: typeof AppAccountPasswordRoute
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
  AppAgentsMineRoute: typeof AppAgentsMineRoute
  AppBuildsBuildIdRoute: typeof AppBuildsBuildIdRoute
  AppChatSessionIdRoute: typeof AppChatSessionIdRoute
  AppFlowsFlowIdRoute: typeof AppFlowsFlowIdRoute
  AppMcpConnectorIdRoute: typeof AppMcpConnectorIdRoute
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsChatContextRoute: typeof AppSettingsChatContextRoute
  AppSettingsOptimizationRoute: typeof AppSettingsOptimizationRoute
  AppSettingsOptimizationTiersRoute: typeof AppSettingsOptimizationTiersRoute
  AppSettingsPasswordRoute: typeof AppSettingsPasswordRoute
  AppSettingsSecretsRoute: typeof AppSettingsSecretsRoute
  AppWorkflowsWorkflowIdRoute: typeof AppWorkflowsWorkflowIdRoute
  AppWorkflowsDraftsRoute: typeof AppWorkflowsDraftsRoute
  AppWorkflowsNewRoute: typeof AppWorkflowsNewRoute
  AppWorkflowsRunsRoute: typeof AppWorkflowsRunsRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
  AppBuildsIndexRoute: typeof AppBuildsIndexRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppFlowsIndexRoute: typeof AppFlowsIndexRoute
  AppMcpIndexRoute: typeof AppMcpIndexRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDeployRoute: AppDeployRoute,
  AppHarnessesRoute: AppHarnessesRoute,
  AppOptimizationRoute: AppOptimizationRoute,
  AppRouterRoute: AppRouterRoute,
  AppStatusRoute: AppStatusRoute,
  AppTokenopsRoute: AppTokenopsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountAppearanceRoute: AppAccountAppearanceRoute,
  AppAccountPasswordRoute: AppAccountPasswordRoute,
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
  AppAgentsMineRoute: AppAgentsMineRoute,
  AppBuildsBuildIdRoute: AppBuildsBuildIdRoute,
  AppChatSessionIdRoute: AppChatSessionIdRoute,
  AppFlowsFlowIdRoute: AppFlowsFlowIdRoute,
  AppMcpConnectorIdRoute: AppMcpConnectorIdRoute,
  AppSessionsSessionIdRoute: AppSessionsSessionIdRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsChatContextRoute: AppSettingsChatContextRoute,
  AppSettingsOptimizationRoute: AppSettingsOptimizationRoute,
  AppSettingsOptimizationTiersRoute: AppSettingsOptimizationTiersRoute,
  AppSettingsPasswordRoute: AppSettingsPasswordRoute,
  AppSettingsSecretsRoute: AppSettingsSecretsRoute,
  AppWorkflowsWorkflowIdRoute: AppWorkflowsWorkflowIdRoute,
  AppWorkflowsDraftsRoute: AppWorkflowsDraftsRoute,
  AppWorkflowsNewRoute: AppWorkflowsNewRoute,
  AppWorkflowsRunsRoute: AppWorkflowsRunsRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
  AppBuildsIndexRoute: AppBuildsIndexRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppFlowsIndexRoute: AppFlowsIndexRoute,
  AppMcpIndexRoute: AppMcpIndexRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
